list: $/yfktn/yfktnutil/models/eventlogger/columns.yaml
modelClass: Yfktn\YfktnUtil\Models\EventLogger
title: EventLogger
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: $/yfktn/yfktnutil/models/eventlogger/filters.yaml
